# Portfolio Application Compose
version: '3.7'

services:
  web:
    image: portfolio-web:latest
    restart: always
    labels:
      # Traefik configuration
      - traefik.http.routers.web.rule=Host(`niccannon.com`)
      - traefik.enabled=true
    depends_on:
      - api

  api:
    image: portfolio-api:latest
    restart: always
    labels:
      # Traefik configuration
      - traefik.http.routers.web.rule=Host(`api.niccannon.com`)
      - traefik.enabled=true
    env_file: .env
    networks:
      - mongodb-network
