# Portfolio Application Compose
version: '3.7'

services:
  web:
    image: repo.treescale.com/nicholascannon1/portfolio/portfolio-web:latest
    container_name: portfolio-web
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    security_opt:
      - no-new-privileges:true
    depends_on:
      - api
    labels:
      # Traefik configuration
      - 'traefik.enable=true'

      # http router config
      - 'traefik.http.routers.portfolio-web.entrypoints=http'
      - 'traefik.http.routers.portfolio-web.rule=Host(`www.niccannon.com`, `niccannon.com`)'
      - 'traefik.http.middlewares.portfolio-web-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.portfolio-web.middlewares=portfolio-web-https-redirect'

      # https router config
      - 'traefik.http.routers.portfolio-web-secure.entrypoints=https'
      - 'traefik.http.routers.portfolio-web-secure.rule=Host(`www.niccannon.com`, `niccannon.com`)'
      - 'traefik.http.routers.portfolio-web-secure.tls=true'
      - 'traefik.http.routers.portfolio-web-secure.tls.certresolver=http'
      - 'traefik.http.routers.portfolio-web-secure.service=portfolio-web'

      - 'traefik.http.services.portfolio-web.loadbalancer.server.port=8080'
      - 'traefik.docker.network=web'

  api:
    image: repo.treescale.com/nicholascannon1/portfolio/portfolio-api:latest
    container_name: portfolio-api
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
      - db_net
    security_opt:
      - no-new-privileges:true
    env_file: .env
    labels:
      # Traefik configuration
      - 'traefik.enable=true'

      # http router config
      - 'traefik.http.routers.portfolio-api.entrypoints=http'
      - 'traefik.http.routers.portfolio-api.rule=Host(`www.api.niccannon.com`, `api.niccannon.com`)'
      - 'traefik.http.middlewares.portfolio-api-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.portfolio-api.middlewares=portfolio-api-https-redirect'

      # https router config
      - 'traefik.http.routers.portfolio-api-secure.entrypoints=https'
      - 'traefik.http.routers.portfolio-api-secure.rule=Host(`www.api.niccannon.com`, `api.niccannon.com`)'
      - 'traefik.http.routers.portfolio-api-secure.tls=true'
      - 'traefik.http.routers.portfolio-api-secure.tls.certresolver=http'
      - 'traefik.http.routers.portfolio-api-secure.service=portfolio-api'

      # modifies the service automatically created for this container
      - 'traefik.http.services.portfolio-api.loadbalancer.server.port=8000'

      # overrides default network used for connections to this container
      - 'traefik.docker.network=web'

networks:
  web:
    external: true
  db_net:
    external: true
    name: mongodb-network
