# Portfolio Application Compose
version: '3.7'

services:
  web:
    image: repo.treescale.com/nicholascannon1/portfolio/portfolio-web:latest
    restart: always
    labels:
      # Traefik configuration
      - traefik.http.routers.web.rule=Host(`niccannon.com`)
      - traefik.enabled=true
    depends_on:
      - api

  api:
    image: repo.treescale.com/nicholascannon1/portfolio/portfolio-api:latest
    restart: always
    labels:
      # Traefik configuration
      - traefik.http.routers.web.rule=Host(`api.niccannon.com`)
      - traefik.enabled=true
    env_file: .env
    networks:
      db_net: {}

networks:
  db_net:
    external: true
    name: mongodb-network
