# Production compose file

version: '3.7'
services:
  api:
    build: .
    env_file: .env
    image: portfolio:v2
    restart: on-failure
    ports:
      - '8081:8000'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./build:/srv/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
